apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana
  namespace: logging
data:
  elasticsearch.yml: |
    cluster.name: ${cluster_name}
   server.host: ${SERVER_HOST}
    elasticsearch.url: ${ELASTICSEARCH_URL}
