apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: elasticsearch
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: elasticsearch
    spec:
      containers:
      - env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ES_JAVA_OPTS
          value: -Xmx256m -Xms256m
        image: topconnector/tc-elasticsearch:v1
        imagePullPolicy: Always
        name: elasticsearch
        ports:
        - containerPort: 9200
        resources: {}
      restartPolicy: Always
status: {}
